# Generated by Django 4.2.7 on 2025-05-18 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logauditoria',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
