# Generated by Django 4.2.7 on 2025-05-18 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ruc', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_eje', models.CharField(max_length=4, verbose_name='Año Ejecución')),
                ('expediente', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('cod', models.CharField(max_length=10)),
                ('nota_pago', models.CharField(max_length=10, verbose_name='Nota de Pago')),
                ('num', models.CharField(max_length=30, verbose_name='Número')),
                ('fuente_recurso', models.CharField(max_length=10, verbose_name='Fuente-Tr')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('glosa', models.TextField()),
                ('folios', models.IntegerField(blank=True, null=True)),
                ('firmado', models.BooleanField(default=False)),
                ('rubro', models.CharField(default='00 RECURSOS ORDINARIOS', max_length=100)),
                ('tipo_recurso', models.CharField(default='0', max_length=50)),
                ('categoria', models.CharField(default='GASTO CAPITAL', max_length=100)),
                ('fase', models.CharField(default='GIRADO', max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('anulado', 'Anulado')], default='pendiente', max_length=20)),
                ('creado_fecha', models.DateTimeField(auto_now_add=True)),
                ('modificado_fecha', models.DateTimeField(auto_now=True)),
                ('area_actual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes_actuales', to='areas.area')),
            ],
            options={
                'verbose_name': 'Comprobante',
                'verbose_name_plural': 'Comprobantes',
                'ordering': ['-fecha', 'nota_pago'],
            },
        ),
    ]
