# Generated by Django 4.2.7 on 2025-05-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('rango_inicial', models.CharField(max_length=10, verbose_name='Del Comp. Pago')),
                ('rango_final', models.CharField(max_length=10, verbose_name='Al Comp. Pago')),
                ('faltantes', models.TextField(blank=True, null=True, verbose_name='Comprobantes Faltantes')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completo', 'Completo'), ('incompleto', 'Incompleto')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_fecha', models.DateTimeField(auto_now_add=True)),
                ('modificado_fecha', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'ordering': ['numero'],
            },
        ),
    ]
